### ISSUE TITLE
"fr50_lite_gn_scratch_icf_wf.py" does not exist

### ISSUE THREAD

**Issue by xuhaibin123** [keshawnhsieh/icartoonface_v2#1]
FileNotFoundErrorFileNotFoundError: : file "/data/baozi/thumbnail_gif_generation/yugao_thumbnail/cartoon_face/icartoonface_v2-master/mmdetection/configs/icartoonface/fr50_lite_gn_scratch_icf_wf.py" does not exist file "/data/baozi/thumbnail_gif_generation/yugao_thumbnail/cartoon_face/icartoonface_v2-master/mmdetection/configs/icartoonface/fr50_lite_gn_scratch_icf_wf.py" does not exist
您好，我在跑训练./mmdetection/tools/dist_train.sh mmdetection/configs/icartoonface/fr50_lite_dcn_gn_scratch_icf_wf.py 2 --seed 0 的时候遇到了“fr50_lite_gn_scratch_icf_wf.py" does not exist的问题，可以提供一下fr50_lite_gn_scratch_icf_wf.py吗，或者是提供一下预训练权重，谢谢您了

**Comment by keshawnhsieh** [comment]
> FileNotFoundErrorFileNotFoundError: : file "/data/baozi/thumbnail_gif_generation/yugao_thumbnail/cartoon_face/icartoonface_v2-master/mmdetection/configs/icartoonface/fr50_lite_gn_scratch_icf_wf.py" does not exist file "/data/baozi/thumbnail_gif_generation/yugao_thumbnail/cartoon_face/icartoonface_v2-master/mmdetection/configs/icartoonface/fr50_lite_gn_scratch_icf_wf.py" does not exist
> 您好，我在跑训练./mmdetection/tools/dist_train.sh mmdetection/configs/icartoonface/fr50_lite_dcn_gn_scratch_icf_wf.py 2 --seed 0 的时候遇到了“fr50_lite_gn_scratch_icf_wf.py" does not exist的问题，可以提供一下fr50_lite_gn_scratch_icf_wf.py吗，或者是提供一下预训练权重，谢谢您了

**Comment by keshawnhsieh** [comment]
Uploaded the missing file.
